### ISSUE TITLE
0.12.36: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [bqplot/bqplot#1592]
**Describe the bug**
Look slike pep617 based build fails

**To Reproduce**
Just execute `python3 -sBm build -w --no-isolation` in source build tree.

**Expected behavior**
pep517 based build should work.

**Screenshots**
<details>

```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
<string>:50: DeprecatedWarning: install_npm is deprecated as of 0.8 and will be removed in 1.0. Use `npm_builder` and `wrap_installers`
<string>:55: DeprecatedWarning: create_cmdclass is deprecated as of 0.8 and will be removed in 1.0. "
Use `wrap_installers` to handle prebuild steps in cmdclass.
Use `get_data_files` to handle data files.
Use `include_package_data=True` and `MANIFEST.in` for package data.

/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
running egg_info
creating bqplot.egg-info
writing bqplot.egg-info/PKG-INFO
writing dependency_links to bqplot.egg-info/dependency_links.txt
writing requirements to bqplot.egg-info/requires.txt
writing top-level names to bqplot.egg-info/top_level.txt
writing manifest file 'bqplot.egg-info/SOURCES.txt'
reading manifest file 'bqplot.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'tests'
adding license file 'LICENSE'
writing manifest file 'bqplot.egg-info/SOURCES.txt'
* Building wheel...
<string>:50: DeprecatedWarning: install_npm is deprecated as of 0.8 and will be removed in 1.0. Use `npm_builder` and `wrap_installers`
<string>:55: DeprecatedWarning: create_cmdclass is deprecated as of 0.8 and will be removed in 1.0. "
Use `wrap_installers` to handle prebuild steps in cmdclass.
Use `get_data_files` to handle data files.
Use `include_package_data=True` and `MANIFEST.in` for package data.

/usr/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
running bdist_wheel
running jsdeps
yarn not found, ignoring yarn.lock file
`npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 413, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 62, in <module>
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 726, in run
    [self.run_command(cmd) for cmd in cmds]
  File "/usr/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 726, in <listcomp>
    [self.run_command(cmd) for cmd in cmds]
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 421, in run
    self.command.run()
  File "/usr/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 345, in run
    c.run()
  File "/usr/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 442, in run
    raise ValueError(("missing files: %s" % missing))
ValueError: missing files: ['share/jupyter/nbextensions/bqplot/index.js', 'share/jupyter/labextensions/bqplot/package.json']

ERROR Backend subprocess exited when trying to invoke build_wheel
```
</details>

**Additional context**
Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.13
anyio                         3.6.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.2.1
attrs                         22.2.0
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
build                         0.9.0
cffi                          1.15.1
charset-normalizer            3.0.1
comm                          0.1.2
coverage                      7.2.1
debugpy                       1.6.6
decorator                     5.1.1
defusedxml                    0.7.1
deprecation                   2.1.0
distro                        1.8.0
docutils                      0.19
entrypoints                   0.4
exceptiongroup                1.0.0
executing                     1.2.0
fastjsonschema                2.16.1
gpg                           1.18.0-unknown
html5lib                      1.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.12.0
iniconfig                     2.0.0
ipykernel                     6.20.2
ipython                       8.6.0
ipython-genutils              0.2.0
ipywidgets                    8.0.3
jedi                          0.18.2
Jinja2                        3.1.2
json5                         0.9.12
jsonschema                    4.17.3
jupyter_client                7.4.9
jupyter_core                  5.2.0
jupyter_packaging             0.12.3
jupyter-server                1.23.3
jupyter-sphinx                0.4.0
jupyterlab                    3.5.1
jupyterlab-pygments           0.1.2
jupyterlab_server             2.18.0
jupyterlab-widgets            3.0.2
libcomps                      0.1.19
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
mistune                       2.0.5
nbclassic                     0.4.8
nbclient                      0.7.2
nbconvert                     7.2.9
nbformat                      5.7.3
nbval                         0.9.6
nest-asyncio                  1.5.6
notebook                      6.5.2
notebook_shim                 0.2.2
numpy                         1.24.2
packaging                     23.0
pandas                        1.5.2
pandocfilters                 1.5.0
parso                         0.8.3
pep517                        0.13.0
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  2.6.0
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.16.0
prompt-toolkit                3.0.36
psutil                        5.9.2
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.14.0
pyrsistent                    0.19.3
pytest                        7.2.2
python-dateutil               2.8.2
pytz                          2022.4
pyzmq                         24.0.1
requests                      2.28.2
rpm                           4.17.0
SciPy                         1.8.1
Send2Trash                    1.8.0
setuptools                    65.6.3
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.2.0
soupsieve                     2.4
Sphinx                        6.1.3
sphinx-rtd-theme              1.1.1
sphinx-thebe                  0.2.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2.dev20230202
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib.jquery          3.0.0
sphinxcontrib-jsmath          1.0.1.dev20230128
sphinxcontrib-qthelp          1.0.3.dev20230128
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
terminado                     0.17.1
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.11.6
tornado                       6.2
traitlets                     5.8.1
traittypes                    0.2.1
urllib3                       1.26.12
wcwidth                       0.2.6
webencodings                  0.5.1
websocket-client              1.5.1
wheel                         0.38.4
widgetsnbextension            4.0.5
zipp                          3.15.0
```
</details>

**Comment by martinRenou** [comment]
You need `yarn` in the build environment

**Comment by kloczek** [comment]
Testeda and it works now.

Thank ypu 👍
