### ISSUE TITLE
RFE: please provide update for `jupyterlab` 4.x

### ISSUE THREAD

**Issue by kloczek** [bqplot/bqplot#1602]
I've been trying to build `bqplot` against `jupyterlab` 4.0.2 after apply patch
```patch
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,3 +1,3 @@
 [build-system]
-requires = ["jupyter_packaging~=0.7.9", "jupyterlab~=3.0", "setuptools>=40.8.0", "wheel"]
+requires = ["jupyter_packaging>=0.7.9", "jupyterlab>=3.0", "setuptools>=40.8.0", "wheel"]
 build-backend = "setuptools.build_meta"
```
However looks like `build is failing
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
running egg_info
running jsdeps
9.6.7
9.6.7
Installing build dependencies with npm.  This may take a while...
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated mumath@3.3.4: Redundant dependency in your project.

added 610 packages, and audited 611 packages in 6s

71 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (12 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> jupyterlab-plotly@5.15.0 build:prod
> npm run build:lib && npm run build:nbextension && npm run build:labextension


> jupyterlab-plotly@5.15.0 build:lib
> tsc


> jupyterlab-plotly@5.15.0 build:nbextension
> webpack --mode=production

asset index.js 3.5 MiB [emitted] [minimized] [big] (name: main) 1 related asset
asset ../../../../javascript/jupyterlab-plotly/lib/Figure.d.ts 8.65 KiB [compared for emit]
asset ../../../../javascript/jupyterlab-plotly/lib/plotly-renderer.d.ts 1.59 KiB [compared for emit]
asset ../../../../javascript/jupyterlab-plotly/lib/version.d.ts 262 bytes [compared for emit]
asset ../../../../javascript/jupyterlab-plotly/lib/jupyterlab-plugin.d.ts 225 bytes [compared for emit]
asset ../../../../javascript/jupyterlab-plotly/lib/index.d.ts 53 bytes [compared for emit]
asset ../../../../javascript/jupyterlab-plotly/lib/extension.d.ts 25 bytes [compared for emit]
runtime modules 1.25 KiB 6 modules
orphan modules 65.7 KiB [orphan] 3 modules
built modules 8.72 MiB [built]
  modules by path ./node_modules/ 8.66 MiB
    ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
    ./node_modules/plotly.js/dist/plotly.js 8.14 MiB [built] [code generated]
  ./src/extension.ts + 3 modules 66.2 KiB [built] [code generated]
  external "@jupyter-widgets/base" 42 bytes [built] [code generated]
  ./package.json 2.1 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index.js (3.5 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (3.5 MiB)
      index.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.75.0 compiled with 3 warnings in 79104 ms

asset index.js 3.5 MiB [emitted] [minimized] [big] (name: main) 1 related asset
asset ../lib/Figure.d.ts 8.65 KiB [compared for emit]
asset ../lib/plotly-renderer.d.ts 1.59 KiB [compared for emit]
asset ../lib/version.d.ts 262 bytes [compared for emit]
asset ../lib/jupyterlab-plugin.d.ts 225 bytes [compared for emit]
asset ../lib/index.d.ts 53 bytes [compared for emit]
asset ../lib/extension.d.ts 25 bytes [compared for emit]
runtime modules 1.25 KiB 6 modules
orphan modules 65.6 KiB [orphan] 2 modules
built modules 8.72 MiB [built]
  modules by path ./node_modules/ 8.66 MiB
    ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
    ./node_modules/plotly.js/dist/plotly.js 8.14 MiB [built] [code generated]
  ./src/index.ts + 2 modules 65.7 KiB [built] [code generated]
  external "@jupyter-widgets/base" 42 bytes [built] [code generated]
  ./package.json 2.1 KiB [built] [code generated]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  index.js (3.5 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (3.5 MiB)
      index.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.75.0 compiled with 3 warnings in 78400 ms

> jupyterlab-plotly@5.15.0 build:labextension
> jupyter labextension build .

Building extension in .
/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py:56: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py:57: UserWarning: ValueError: Extensions require a devDependency on @jupyterlab/builder@^4.0.2, you have a dependency on 3.6.1
  warnings.warn(msg[-1].strip())
/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py:58: UserWarning: See the log file for details: /tmp/jupyterlab-debug-uvamlkhv.log
  warnings.warn(f"See the log file for details: {log_path!s}")
rebuilding js and css failed
missing files: ['/home/tkloczko/rpmbuild/BUILD/plotly.py-5.15.0/packages/python/plotly/jupyterlab_plotly/labextension/package.json']
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 495, in <module>
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 104, in run
  File "<string>", line 97, in run
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "<string>", line 190, in run
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build:prod']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by martinRenou** [comment]
This will unfortunately not work until ipywidgets is released allowing this.

Is there any reason for wanting to build against JupyterLab 4? Note that if you build bqplot against JupyterLab 3, and install the produced wheel in a JupyterLab 4 environment, it will **just work**

**Comment by martinRenou** [comment]
This is now possible since https://github.com/bqplot/bqplot/pull/1608
